/********************************************************************************
** Form generated from reading UI file 'DlgRouteParam.ui'
**
** Created by: Qt User Interface Compiler version 5.9.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DLGROUTEPARAM_H
#define UI_DLGROUTEPARAM_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_DlgRouteParam
{
public:
    QPlainTextEdit *plainTextEdit_Show;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QPushButton *pushButton_RunBackOffSetY;
    QLineEdit *lineEdit_Circle14;
    QLineEdit *lineEdit_P1;
    QLineEdit *lineEdit_P4;
    QPushButton *pushButton_Circle14;
    QPushButton *pushButton_P3;
    QPushButton *pushButton_P2;
    QPushButton *pushButton_BackGrat;
    QLineEdit *lineEdit_BackGrat;
    QLineEdit *lineEdit_RunBackOffSetY;
    QLineEdit *lineEdit_FrontGrat;
    QLineEdit *lineEdit_LightOpen;
    QPushButton *pushButton_P1;
    QLineEdit *lineEdit_P5;
    QPushButton *pushButton_P4;
    QPushButton *pushButton_LightOpen;
    QPushButton *pushButton_FrontGrat;
    QLineEdit *lineEdit_P2;
    QPushButton *pushButton_P5;
    QLineEdit *lineEdit_P3;
    QWidget *page_2;
    QPushButton *pushButton_Long;
    QLineEdit *lineEdit_Long;
    QPushButton *pushButton_FrontBackImageHeight;
    QLineEdit *lineEdit_FrontBackImageHeight;
    QPushButton *pushButton_Width;
    QLineEdit *lineEdit_Width;
    QPushButton *pushButton_ResetPointX;
    QLineEdit *lineEdit_ResetPointX;
    QPushButton *pushButton_ResetPointY;
    QLineEdit *lineEdit_ResetPointY;
    QPushButton *pushButton_ResetPointZ;
    QLineEdit *lineEdit_ResetPointZ;
    QLineEdit *lineEdit_GetPointX;
    QPushButton *pushButton_GetPointZ;
    QLineEdit *lineEdit_GetPointY;
    QLineEdit *lineEdit_GetPointZ;
    QPushButton *pushButton_GetPointY;
    QPushButton *pushButton_GetPointX;
    QWidget *page_3;
    QPushButton *pushButton_FrontOffSetX;
    QLineEdit *lineEdit_FrontOffSetX;
    QPushButton *pushButton_FrontOffSetY;
    QLineEdit *lineEdit_FrontOffSetY;
    QPushButton *pushButton_FrontOffSetZ;
    QLineEdit *lineEdit_FrontOffSetZ;
    QWidget *page_4;
    QPushButton *pushButton_FrameOffSetX1;
    QLineEdit *lineEdit_FrameOffSetX1;
    QPushButton *pushButton_FrameOffSetZ1;
    QLineEdit *lineEdit_FrameOffSetZ1;
    QLineEdit *lineEdit_FrameStep;
    QPushButton *pushButton_FrameOffSetY1;
    QPushButton *pushButton_FrameStep;
    QLineEdit *lineEdit_FrameOffSetY1;
    QLineEdit *lineEdit_FrameOffSetZ2;
    QPushButton *pushButton_FrameOffSetY2;
    QPushButton *pushButton_FrameOffSetX2;
    QLineEdit *lineEdit_FrameOffSetX2;
    QPushButton *pushButton_FrameOffSetZ2;
    QLineEdit *lineEdit_FrameOffSetY2;
    QLineEdit *lineEdit_FrameOffSetY3;
    QPushButton *pushButton_FrameOffSetX3;
    QLineEdit *lineEdit_FrameOffSetX3;
    QPushButton *pushButton_FrameOffSetY3;
    QPushButton *pushButton_FrameOffSetZ3;
    QLineEdit *lineEdit_FrameOffSetZ3;
    QPushButton *pushButton_FrameOffSetZ4;
    QLineEdit *lineEdit_FrameOffSetY4;
    QLineEdit *lineEdit_FrameOffSetZ4;
    QPushButton *pushButton_FrameOffSetX4;
    QPushButton *pushButton_FrameOffSetY4;
    QLineEdit *lineEdit_FrameOffSetX4;
    QWidget *page_5;
    QPushButton *pushButton_CylinderOffSetX;
    QLineEdit *lineEdit_CylinderOffSetX;
    QPushButton *pushButton_CylinderOffSetY;
    QLineEdit *lineEdit_CylinderOffSetY;
    QPushButton *pushButton_CylinderOffSetZ;
    QLineEdit *lineEdit_CylinderOffSetZ;
    QPushButton *pushButton_CameraOffSetZ;
    QLineEdit *lineEdit_CameraOffSetY;
    QLineEdit *lineEdit_CameraOffSetZ;
    QPushButton *pushButton_CameraOffSetX;
    QPushButton *pushButton_CameraOffSetY;
    QLineEdit *lineEdit_CameraOffSetX;
    QWidget *page_6;
    QPushButton *pushButton_BackOffSetX;
    QLineEdit *lineEdit_BackOffSetX;
    QPushButton *pushButton_BackOffSetY;
    QLineEdit *lineEdit_BackOffSetY;
    QPushButton *pushButton_BackOffSetZ;
    QLineEdit *lineEdit_BackOffSetZ;
    QWidget *page_7;
    QPushButton *pushButton_FrameCornerOffSetY1;
    QPushButton *pushButton_FrameCornerOffSetX1;
    QLineEdit *lineEdit_FrameCornerOffSetX1;
    QLineEdit *lineEdit_FrameCornerOffSetZ1;
    QPushButton *pushButton_FrameCornerOffSetZ1;
    QLineEdit *lineEdit_FrameCornerOffSetY1;
    QPushButton *pushButton_FrameCornerOffSetZ2;
    QLineEdit *lineEdit_FrameCornerOffSetZ2;
    QLineEdit *lineEdit_FrameCornerOffSetX2;
    QLineEdit *lineEdit_FrameCornerOffSetY2;
    QPushButton *pushButton_FrameCornerOffSetY2;
    QPushButton *pushButton_FrameCornerOffSetX2;
    QPushButton *pushButton_FrameCornerOffSetZ3;
    QPushButton *pushButton_FrameCornerOffSetY3;
    QLineEdit *lineEdit_FrameCornerOffSetY3;
    QLineEdit *lineEdit_FrameCornerOffSetZ3;
    QPushButton *pushButton_FrameCornerOffSetX3;
    QLineEdit *lineEdit_FrameCornerOffSetX3;
    QPushButton *pushButton_FrameCornerOffSetZ4;
    QLineEdit *lineEdit_FrameCornerOffSetY4;
    QPushButton *pushButton_FrameCornerOffSetX4;
    QLineEdit *lineEdit_FrameCornerOffSetX4;
    QPushButton *pushButton_FrameCornerOffSetY4;
    QLineEdit *lineEdit_FrameCornerOffSetZ4;
    QPushButton *pushButton_PageIndex0;
    QPushButton *pushButton_PageIndex1;
    QPushButton *pushButton_PageIndex2;
    QPushButton *pushButton_PageIndex3;
    QPushButton *pushButton_PageIndex4;
    QPushButton *pushButton_PageIndex5;
    QPushButton *pushButton_PageIndex6;

    void setupUi(QDialog *DlgRouteParam)
    {
        if (DlgRouteParam->objectName().isEmpty())
            DlgRouteParam->setObjectName(QStringLiteral("DlgRouteParam"));
        DlgRouteParam->resize(1083, 617);
        DlgRouteParam->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        plainTextEdit_Show = new QPlainTextEdit(DlgRouteParam);
        plainTextEdit_Show->setObjectName(QStringLiteral("plainTextEdit_Show"));
        plainTextEdit_Show->setGeometry(QRect(790, 10, 271, 401));
        stackedWidget = new QStackedWidget(DlgRouteParam);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(140, 10, 641, 711));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        pushButton_RunBackOffSetY = new QPushButton(page);
        pushButton_RunBackOffSetY->setObjectName(QStringLiteral("pushButton_RunBackOffSetY"));
        pushButton_RunBackOffSetY->setGeometry(QRect(470, 260, 131, 31));
        pushButton_RunBackOffSetY->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_Circle14 = new QLineEdit(page);
        lineEdit_Circle14->setObjectName(QStringLiteral("lineEdit_Circle14"));
        lineEdit_Circle14->setGeometry(QRect(340, 200, 101, 31));
        lineEdit_Circle14->setAlignment(Qt::AlignCenter);
        lineEdit_P1 = new QLineEdit(page);
        lineEdit_P1->setObjectName(QStringLiteral("lineEdit_P1"));
        lineEdit_P1->setGeometry(QRect(30, 20, 101, 31));
        lineEdit_P1->setAlignment(Qt::AlignCenter);
        lineEdit_P4 = new QLineEdit(page);
        lineEdit_P4->setObjectName(QStringLiteral("lineEdit_P4"));
        lineEdit_P4->setGeometry(QRect(30, 200, 101, 31));
        lineEdit_P4->setAlignment(Qt::AlignCenter);
        pushButton_Circle14 = new QPushButton(page);
        pushButton_Circle14->setObjectName(QStringLiteral("pushButton_Circle14"));
        pushButton_Circle14->setGeometry(QRect(470, 200, 131, 31));
        pushButton_Circle14->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_P3 = new QPushButton(page);
        pushButton_P3->setObjectName(QStringLiteral("pushButton_P3"));
        pushButton_P3->setGeometry(QRect(160, 140, 131, 31));
        pushButton_P3->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_P2 = new QPushButton(page);
        pushButton_P2->setObjectName(QStringLiteral("pushButton_P2"));
        pushButton_P2->setGeometry(QRect(160, 80, 131, 31));
        pushButton_P2->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_BackGrat = new QPushButton(page);
        pushButton_BackGrat->setObjectName(QStringLiteral("pushButton_BackGrat"));
        pushButton_BackGrat->setGeometry(QRect(470, 80, 131, 31));
        pushButton_BackGrat->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_BackGrat = new QLineEdit(page);
        lineEdit_BackGrat->setObjectName(QStringLiteral("lineEdit_BackGrat"));
        lineEdit_BackGrat->setGeometry(QRect(340, 80, 101, 31));
        lineEdit_BackGrat->setAlignment(Qt::AlignCenter);
        lineEdit_RunBackOffSetY = new QLineEdit(page);
        lineEdit_RunBackOffSetY->setObjectName(QStringLiteral("lineEdit_RunBackOffSetY"));
        lineEdit_RunBackOffSetY->setGeometry(QRect(340, 260, 101, 31));
        lineEdit_RunBackOffSetY->setAlignment(Qt::AlignCenter);
        lineEdit_FrontGrat = new QLineEdit(page);
        lineEdit_FrontGrat->setObjectName(QStringLiteral("lineEdit_FrontGrat"));
        lineEdit_FrontGrat->setGeometry(QRect(340, 20, 101, 31));
        lineEdit_FrontGrat->setAlignment(Qt::AlignCenter);
        lineEdit_LightOpen = new QLineEdit(page);
        lineEdit_LightOpen->setObjectName(QStringLiteral("lineEdit_LightOpen"));
        lineEdit_LightOpen->setGeometry(QRect(340, 140, 101, 31));
        lineEdit_LightOpen->setAlignment(Qt::AlignCenter);
        pushButton_P1 = new QPushButton(page);
        pushButton_P1->setObjectName(QStringLiteral("pushButton_P1"));
        pushButton_P1->setGeometry(QRect(160, 20, 131, 31));
        pushButton_P1->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_P5 = new QLineEdit(page);
        lineEdit_P5->setObjectName(QStringLiteral("lineEdit_P5"));
        lineEdit_P5->setGeometry(QRect(30, 260, 101, 31));
        lineEdit_P5->setAlignment(Qt::AlignCenter);
        pushButton_P4 = new QPushButton(page);
        pushButton_P4->setObjectName(QStringLiteral("pushButton_P4"));
        pushButton_P4->setGeometry(QRect(160, 200, 131, 31));
        pushButton_P4->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_LightOpen = new QPushButton(page);
        pushButton_LightOpen->setObjectName(QStringLiteral("pushButton_LightOpen"));
        pushButton_LightOpen->setGeometry(QRect(470, 140, 131, 31));
        pushButton_LightOpen->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_FrontGrat = new QPushButton(page);
        pushButton_FrontGrat->setObjectName(QStringLiteral("pushButton_FrontGrat"));
        pushButton_FrontGrat->setGeometry(QRect(470, 20, 131, 31));
        pushButton_FrontGrat->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_P2 = new QLineEdit(page);
        lineEdit_P2->setObjectName(QStringLiteral("lineEdit_P2"));
        lineEdit_P2->setGeometry(QRect(30, 80, 101, 31));
        lineEdit_P2->setAlignment(Qt::AlignCenter);
        pushButton_P5 = new QPushButton(page);
        pushButton_P5->setObjectName(QStringLiteral("pushButton_P5"));
        pushButton_P5->setGeometry(QRect(160, 260, 131, 31));
        pushButton_P5->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_P3 = new QLineEdit(page);
        lineEdit_P3->setObjectName(QStringLiteral("lineEdit_P3"));
        lineEdit_P3->setGeometry(QRect(30, 140, 101, 31));
        lineEdit_P3->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        pushButton_Long = new QPushButton(page_2);
        pushButton_Long->setObjectName(QStringLiteral("pushButton_Long"));
        pushButton_Long->setGeometry(QRect(160, 20, 131, 31));
        pushButton_Long->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_Long = new QLineEdit(page_2);
        lineEdit_Long->setObjectName(QStringLiteral("lineEdit_Long"));
        lineEdit_Long->setGeometry(QRect(30, 20, 101, 31));
        lineEdit_Long->setAlignment(Qt::AlignCenter);
        pushButton_FrontBackImageHeight = new QPushButton(page_2);
        pushButton_FrontBackImageHeight->setObjectName(QStringLiteral("pushButton_FrontBackImageHeight"));
        pushButton_FrontBackImageHeight->setGeometry(QRect(160, 80, 131, 31));
        pushButton_FrontBackImageHeight->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrontBackImageHeight = new QLineEdit(page_2);
        lineEdit_FrontBackImageHeight->setObjectName(QStringLiteral("lineEdit_FrontBackImageHeight"));
        lineEdit_FrontBackImageHeight->setGeometry(QRect(30, 80, 101, 31));
        lineEdit_FrontBackImageHeight->setAlignment(Qt::AlignCenter);
        pushButton_Width = new QPushButton(page_2);
        pushButton_Width->setObjectName(QStringLiteral("pushButton_Width"));
        pushButton_Width->setGeometry(QRect(470, 20, 131, 31));
        pushButton_Width->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_Width = new QLineEdit(page_2);
        lineEdit_Width->setObjectName(QStringLiteral("lineEdit_Width"));
        lineEdit_Width->setGeometry(QRect(340, 20, 101, 31));
        lineEdit_Width->setAlignment(Qt::AlignCenter);
        pushButton_ResetPointX = new QPushButton(page_2);
        pushButton_ResetPointX->setObjectName(QStringLiteral("pushButton_ResetPointX"));
        pushButton_ResetPointX->setGeometry(QRect(160, 140, 131, 31));
        pushButton_ResetPointX->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_ResetPointX = new QLineEdit(page_2);
        lineEdit_ResetPointX->setObjectName(QStringLiteral("lineEdit_ResetPointX"));
        lineEdit_ResetPointX->setGeometry(QRect(30, 140, 101, 31));
        lineEdit_ResetPointX->setAlignment(Qt::AlignCenter);
        pushButton_ResetPointY = new QPushButton(page_2);
        pushButton_ResetPointY->setObjectName(QStringLiteral("pushButton_ResetPointY"));
        pushButton_ResetPointY->setGeometry(QRect(160, 200, 131, 31));
        pushButton_ResetPointY->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_ResetPointY = new QLineEdit(page_2);
        lineEdit_ResetPointY->setObjectName(QStringLiteral("lineEdit_ResetPointY"));
        lineEdit_ResetPointY->setGeometry(QRect(30, 200, 101, 31));
        lineEdit_ResetPointY->setAlignment(Qt::AlignCenter);
        pushButton_ResetPointZ = new QPushButton(page_2);
        pushButton_ResetPointZ->setObjectName(QStringLiteral("pushButton_ResetPointZ"));
        pushButton_ResetPointZ->setGeometry(QRect(160, 260, 131, 31));
        pushButton_ResetPointZ->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_ResetPointZ = new QLineEdit(page_2);
        lineEdit_ResetPointZ->setObjectName(QStringLiteral("lineEdit_ResetPointZ"));
        lineEdit_ResetPointZ->setGeometry(QRect(30, 260, 101, 31));
        lineEdit_ResetPointZ->setAlignment(Qt::AlignCenter);
        lineEdit_GetPointX = new QLineEdit(page_2);
        lineEdit_GetPointX->setObjectName(QStringLiteral("lineEdit_GetPointX"));
        lineEdit_GetPointX->setGeometry(QRect(340, 140, 101, 31));
        lineEdit_GetPointX->setAlignment(Qt::AlignCenter);
        pushButton_GetPointZ = new QPushButton(page_2);
        pushButton_GetPointZ->setObjectName(QStringLiteral("pushButton_GetPointZ"));
        pushButton_GetPointZ->setGeometry(QRect(470, 260, 131, 31));
        pushButton_GetPointZ->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_GetPointY = new QLineEdit(page_2);
        lineEdit_GetPointY->setObjectName(QStringLiteral("lineEdit_GetPointY"));
        lineEdit_GetPointY->setGeometry(QRect(340, 200, 101, 31));
        lineEdit_GetPointY->setAlignment(Qt::AlignCenter);
        lineEdit_GetPointZ = new QLineEdit(page_2);
        lineEdit_GetPointZ->setObjectName(QStringLiteral("lineEdit_GetPointZ"));
        lineEdit_GetPointZ->setGeometry(QRect(340, 260, 101, 31));
        lineEdit_GetPointZ->setAlignment(Qt::AlignCenter);
        pushButton_GetPointY = new QPushButton(page_2);
        pushButton_GetPointY->setObjectName(QStringLiteral("pushButton_GetPointY"));
        pushButton_GetPointY->setGeometry(QRect(470, 200, 131, 31));
        pushButton_GetPointY->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_GetPointX = new QPushButton(page_2);
        pushButton_GetPointX->setObjectName(QStringLiteral("pushButton_GetPointX"));
        pushButton_GetPointX->setGeometry(QRect(470, 140, 131, 31));
        pushButton_GetPointX->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        pushButton_FrontOffSetX = new QPushButton(page_3);
        pushButton_FrontOffSetX->setObjectName(QStringLiteral("pushButton_FrontOffSetX"));
        pushButton_FrontOffSetX->setGeometry(QRect(160, 20, 131, 31));
        pushButton_FrontOffSetX->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrontOffSetX = new QLineEdit(page_3);
        lineEdit_FrontOffSetX->setObjectName(QStringLiteral("lineEdit_FrontOffSetX"));
        lineEdit_FrontOffSetX->setGeometry(QRect(30, 20, 101, 31));
        lineEdit_FrontOffSetX->setAlignment(Qt::AlignCenter);
        pushButton_FrontOffSetY = new QPushButton(page_3);
        pushButton_FrontOffSetY->setObjectName(QStringLiteral("pushButton_FrontOffSetY"));
        pushButton_FrontOffSetY->setGeometry(QRect(160, 80, 131, 31));
        pushButton_FrontOffSetY->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrontOffSetY = new QLineEdit(page_3);
        lineEdit_FrontOffSetY->setObjectName(QStringLiteral("lineEdit_FrontOffSetY"));
        lineEdit_FrontOffSetY->setGeometry(QRect(30, 80, 101, 31));
        lineEdit_FrontOffSetY->setAlignment(Qt::AlignCenter);
        pushButton_FrontOffSetZ = new QPushButton(page_3);
        pushButton_FrontOffSetZ->setObjectName(QStringLiteral("pushButton_FrontOffSetZ"));
        pushButton_FrontOffSetZ->setGeometry(QRect(160, 140, 131, 31));
        pushButton_FrontOffSetZ->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrontOffSetZ = new QLineEdit(page_3);
        lineEdit_FrontOffSetZ->setObjectName(QStringLiteral("lineEdit_FrontOffSetZ"));
        lineEdit_FrontOffSetZ->setGeometry(QRect(30, 140, 101, 31));
        lineEdit_FrontOffSetZ->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        pushButton_FrameOffSetX1 = new QPushButton(page_4);
        pushButton_FrameOffSetX1->setObjectName(QStringLiteral("pushButton_FrameOffSetX1"));
        pushButton_FrameOffSetX1->setGeometry(QRect(160, 20, 131, 31));
        pushButton_FrameOffSetX1->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameOffSetX1 = new QLineEdit(page_4);
        lineEdit_FrameOffSetX1->setObjectName(QStringLiteral("lineEdit_FrameOffSetX1"));
        lineEdit_FrameOffSetX1->setGeometry(QRect(30, 20, 101, 31));
        lineEdit_FrameOffSetX1->setAlignment(Qt::AlignCenter);
        pushButton_FrameOffSetZ1 = new QPushButton(page_4);
        pushButton_FrameOffSetZ1->setObjectName(QStringLiteral("pushButton_FrameOffSetZ1"));
        pushButton_FrameOffSetZ1->setGeometry(QRect(160, 140, 131, 31));
        pushButton_FrameOffSetZ1->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameOffSetZ1 = new QLineEdit(page_4);
        lineEdit_FrameOffSetZ1->setObjectName(QStringLiteral("lineEdit_FrameOffSetZ1"));
        lineEdit_FrameOffSetZ1->setGeometry(QRect(30, 140, 101, 31));
        lineEdit_FrameOffSetZ1->setAlignment(Qt::AlignCenter);
        lineEdit_FrameStep = new QLineEdit(page_4);
        lineEdit_FrameStep->setObjectName(QStringLiteral("lineEdit_FrameStep"));
        lineEdit_FrameStep->setGeometry(QRect(190, 370, 101, 31));
        lineEdit_FrameStep->setAlignment(Qt::AlignCenter);
        pushButton_FrameOffSetY1 = new QPushButton(page_4);
        pushButton_FrameOffSetY1->setObjectName(QStringLiteral("pushButton_FrameOffSetY1"));
        pushButton_FrameOffSetY1->setGeometry(QRect(160, 80, 131, 31));
        pushButton_FrameOffSetY1->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_FrameStep = new QPushButton(page_4);
        pushButton_FrameStep->setObjectName(QStringLiteral("pushButton_FrameStep"));
        pushButton_FrameStep->setGeometry(QRect(320, 370, 131, 31));
        pushButton_FrameStep->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameOffSetY1 = new QLineEdit(page_4);
        lineEdit_FrameOffSetY1->setObjectName(QStringLiteral("lineEdit_FrameOffSetY1"));
        lineEdit_FrameOffSetY1->setGeometry(QRect(30, 80, 101, 31));
        lineEdit_FrameOffSetY1->setAlignment(Qt::AlignCenter);
        lineEdit_FrameOffSetZ2 = new QLineEdit(page_4);
        lineEdit_FrameOffSetZ2->setObjectName(QStringLiteral("lineEdit_FrameOffSetZ2"));
        lineEdit_FrameOffSetZ2->setGeometry(QRect(330, 140, 101, 31));
        lineEdit_FrameOffSetZ2->setAlignment(Qt::AlignCenter);
        pushButton_FrameOffSetY2 = new QPushButton(page_4);
        pushButton_FrameOffSetY2->setObjectName(QStringLiteral("pushButton_FrameOffSetY2"));
        pushButton_FrameOffSetY2->setGeometry(QRect(460, 80, 131, 31));
        pushButton_FrameOffSetY2->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_FrameOffSetX2 = new QPushButton(page_4);
        pushButton_FrameOffSetX2->setObjectName(QStringLiteral("pushButton_FrameOffSetX2"));
        pushButton_FrameOffSetX2->setGeometry(QRect(460, 20, 131, 31));
        pushButton_FrameOffSetX2->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameOffSetX2 = new QLineEdit(page_4);
        lineEdit_FrameOffSetX2->setObjectName(QStringLiteral("lineEdit_FrameOffSetX2"));
        lineEdit_FrameOffSetX2->setGeometry(QRect(330, 20, 101, 31));
        lineEdit_FrameOffSetX2->setAlignment(Qt::AlignCenter);
        pushButton_FrameOffSetZ2 = new QPushButton(page_4);
        pushButton_FrameOffSetZ2->setObjectName(QStringLiteral("pushButton_FrameOffSetZ2"));
        pushButton_FrameOffSetZ2->setGeometry(QRect(460, 140, 131, 31));
        pushButton_FrameOffSetZ2->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameOffSetY2 = new QLineEdit(page_4);
        lineEdit_FrameOffSetY2->setObjectName(QStringLiteral("lineEdit_FrameOffSetY2"));
        lineEdit_FrameOffSetY2->setGeometry(QRect(330, 80, 101, 31));
        lineEdit_FrameOffSetY2->setAlignment(Qt::AlignCenter);
        lineEdit_FrameOffSetY3 = new QLineEdit(page_4);
        lineEdit_FrameOffSetY3->setObjectName(QStringLiteral("lineEdit_FrameOffSetY3"));
        lineEdit_FrameOffSetY3->setGeometry(QRect(30, 260, 101, 31));
        lineEdit_FrameOffSetY3->setAlignment(Qt::AlignCenter);
        pushButton_FrameOffSetX3 = new QPushButton(page_4);
        pushButton_FrameOffSetX3->setObjectName(QStringLiteral("pushButton_FrameOffSetX3"));
        pushButton_FrameOffSetX3->setGeometry(QRect(160, 200, 131, 31));
        pushButton_FrameOffSetX3->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameOffSetX3 = new QLineEdit(page_4);
        lineEdit_FrameOffSetX3->setObjectName(QStringLiteral("lineEdit_FrameOffSetX3"));
        lineEdit_FrameOffSetX3->setGeometry(QRect(30, 200, 101, 31));
        lineEdit_FrameOffSetX3->setAlignment(Qt::AlignCenter);
        pushButton_FrameOffSetY3 = new QPushButton(page_4);
        pushButton_FrameOffSetY3->setObjectName(QStringLiteral("pushButton_FrameOffSetY3"));
        pushButton_FrameOffSetY3->setGeometry(QRect(160, 260, 131, 31));
        pushButton_FrameOffSetY3->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_FrameOffSetZ3 = new QPushButton(page_4);
        pushButton_FrameOffSetZ3->setObjectName(QStringLiteral("pushButton_FrameOffSetZ3"));
        pushButton_FrameOffSetZ3->setGeometry(QRect(160, 320, 131, 31));
        pushButton_FrameOffSetZ3->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameOffSetZ3 = new QLineEdit(page_4);
        lineEdit_FrameOffSetZ3->setObjectName(QStringLiteral("lineEdit_FrameOffSetZ3"));
        lineEdit_FrameOffSetZ3->setGeometry(QRect(30, 320, 101, 31));
        lineEdit_FrameOffSetZ3->setAlignment(Qt::AlignCenter);
        pushButton_FrameOffSetZ4 = new QPushButton(page_4);
        pushButton_FrameOffSetZ4->setObjectName(QStringLiteral("pushButton_FrameOffSetZ4"));
        pushButton_FrameOffSetZ4->setGeometry(QRect(460, 320, 131, 31));
        pushButton_FrameOffSetZ4->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameOffSetY4 = new QLineEdit(page_4);
        lineEdit_FrameOffSetY4->setObjectName(QStringLiteral("lineEdit_FrameOffSetY4"));
        lineEdit_FrameOffSetY4->setGeometry(QRect(330, 260, 101, 31));
        lineEdit_FrameOffSetY4->setAlignment(Qt::AlignCenter);
        lineEdit_FrameOffSetZ4 = new QLineEdit(page_4);
        lineEdit_FrameOffSetZ4->setObjectName(QStringLiteral("lineEdit_FrameOffSetZ4"));
        lineEdit_FrameOffSetZ4->setGeometry(QRect(330, 320, 101, 31));
        lineEdit_FrameOffSetZ4->setAlignment(Qt::AlignCenter);
        pushButton_FrameOffSetX4 = new QPushButton(page_4);
        pushButton_FrameOffSetX4->setObjectName(QStringLiteral("pushButton_FrameOffSetX4"));
        pushButton_FrameOffSetX4->setGeometry(QRect(460, 200, 131, 31));
        pushButton_FrameOffSetX4->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_FrameOffSetY4 = new QPushButton(page_4);
        pushButton_FrameOffSetY4->setObjectName(QStringLiteral("pushButton_FrameOffSetY4"));
        pushButton_FrameOffSetY4->setGeometry(QRect(460, 260, 131, 31));
        pushButton_FrameOffSetY4->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameOffSetX4 = new QLineEdit(page_4);
        lineEdit_FrameOffSetX4->setObjectName(QStringLiteral("lineEdit_FrameOffSetX4"));
        lineEdit_FrameOffSetX4->setGeometry(QRect(330, 200, 101, 31));
        lineEdit_FrameOffSetX4->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        pushButton_CylinderOffSetX = new QPushButton(page_5);
        pushButton_CylinderOffSetX->setObjectName(QStringLiteral("pushButton_CylinderOffSetX"));
        pushButton_CylinderOffSetX->setGeometry(QRect(160, 20, 131, 31));
        pushButton_CylinderOffSetX->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_CylinderOffSetX = new QLineEdit(page_5);
        lineEdit_CylinderOffSetX->setObjectName(QStringLiteral("lineEdit_CylinderOffSetX"));
        lineEdit_CylinderOffSetX->setGeometry(QRect(30, 20, 101, 31));
        lineEdit_CylinderOffSetX->setAlignment(Qt::AlignCenter);
        pushButton_CylinderOffSetY = new QPushButton(page_5);
        pushButton_CylinderOffSetY->setObjectName(QStringLiteral("pushButton_CylinderOffSetY"));
        pushButton_CylinderOffSetY->setGeometry(QRect(160, 80, 131, 31));
        pushButton_CylinderOffSetY->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_CylinderOffSetY = new QLineEdit(page_5);
        lineEdit_CylinderOffSetY->setObjectName(QStringLiteral("lineEdit_CylinderOffSetY"));
        lineEdit_CylinderOffSetY->setGeometry(QRect(30, 80, 101, 31));
        lineEdit_CylinderOffSetY->setAlignment(Qt::AlignCenter);
        pushButton_CylinderOffSetZ = new QPushButton(page_5);
        pushButton_CylinderOffSetZ->setObjectName(QStringLiteral("pushButton_CylinderOffSetZ"));
        pushButton_CylinderOffSetZ->setGeometry(QRect(160, 140, 131, 31));
        pushButton_CylinderOffSetZ->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_CylinderOffSetZ = new QLineEdit(page_5);
        lineEdit_CylinderOffSetZ->setObjectName(QStringLiteral("lineEdit_CylinderOffSetZ"));
        lineEdit_CylinderOffSetZ->setGeometry(QRect(30, 140, 101, 31));
        lineEdit_CylinderOffSetZ->setAlignment(Qt::AlignCenter);
        pushButton_CameraOffSetZ = new QPushButton(page_5);
        pushButton_CameraOffSetZ->setObjectName(QStringLiteral("pushButton_CameraOffSetZ"));
        pushButton_CameraOffSetZ->setGeometry(QRect(470, 140, 131, 31));
        pushButton_CameraOffSetZ->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_CameraOffSetY = new QLineEdit(page_5);
        lineEdit_CameraOffSetY->setObjectName(QStringLiteral("lineEdit_CameraOffSetY"));
        lineEdit_CameraOffSetY->setGeometry(QRect(340, 80, 101, 31));
        lineEdit_CameraOffSetY->setAlignment(Qt::AlignCenter);
        lineEdit_CameraOffSetZ = new QLineEdit(page_5);
        lineEdit_CameraOffSetZ->setObjectName(QStringLiteral("lineEdit_CameraOffSetZ"));
        lineEdit_CameraOffSetZ->setGeometry(QRect(340, 140, 101, 31));
        lineEdit_CameraOffSetZ->setAlignment(Qt::AlignCenter);
        pushButton_CameraOffSetX = new QPushButton(page_5);
        pushButton_CameraOffSetX->setObjectName(QStringLiteral("pushButton_CameraOffSetX"));
        pushButton_CameraOffSetX->setGeometry(QRect(470, 20, 131, 31));
        pushButton_CameraOffSetX->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_CameraOffSetY = new QPushButton(page_5);
        pushButton_CameraOffSetY->setObjectName(QStringLiteral("pushButton_CameraOffSetY"));
        pushButton_CameraOffSetY->setGeometry(QRect(470, 80, 131, 31));
        pushButton_CameraOffSetY->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_CameraOffSetX = new QLineEdit(page_5);
        lineEdit_CameraOffSetX->setObjectName(QStringLiteral("lineEdit_CameraOffSetX"));
        lineEdit_CameraOffSetX->setGeometry(QRect(340, 20, 101, 31));
        lineEdit_CameraOffSetX->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        pushButton_BackOffSetX = new QPushButton(page_6);
        pushButton_BackOffSetX->setObjectName(QStringLiteral("pushButton_BackOffSetX"));
        pushButton_BackOffSetX->setGeometry(QRect(160, 20, 131, 31));
        pushButton_BackOffSetX->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_BackOffSetX = new QLineEdit(page_6);
        lineEdit_BackOffSetX->setObjectName(QStringLiteral("lineEdit_BackOffSetX"));
        lineEdit_BackOffSetX->setGeometry(QRect(30, 20, 101, 31));
        lineEdit_BackOffSetX->setAlignment(Qt::AlignCenter);
        pushButton_BackOffSetY = new QPushButton(page_6);
        pushButton_BackOffSetY->setObjectName(QStringLiteral("pushButton_BackOffSetY"));
        pushButton_BackOffSetY->setGeometry(QRect(160, 80, 131, 31));
        pushButton_BackOffSetY->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_BackOffSetY = new QLineEdit(page_6);
        lineEdit_BackOffSetY->setObjectName(QStringLiteral("lineEdit_BackOffSetY"));
        lineEdit_BackOffSetY->setGeometry(QRect(30, 80, 101, 31));
        lineEdit_BackOffSetY->setAlignment(Qt::AlignCenter);
        pushButton_BackOffSetZ = new QPushButton(page_6);
        pushButton_BackOffSetZ->setObjectName(QStringLiteral("pushButton_BackOffSetZ"));
        pushButton_BackOffSetZ->setGeometry(QRect(160, 140, 131, 31));
        pushButton_BackOffSetZ->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_BackOffSetZ = new QLineEdit(page_6);
        lineEdit_BackOffSetZ->setObjectName(QStringLiteral("lineEdit_BackOffSetZ"));
        lineEdit_BackOffSetZ->setGeometry(QRect(30, 140, 101, 31));
        lineEdit_BackOffSetZ->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        pushButton_FrameCornerOffSetY1 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetY1->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetY1"));
        pushButton_FrameCornerOffSetY1->setGeometry(QRect(160, 80, 131, 31));
        pushButton_FrameCornerOffSetY1->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_FrameCornerOffSetX1 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetX1->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetX1"));
        pushButton_FrameCornerOffSetX1->setGeometry(QRect(160, 20, 131, 31));
        pushButton_FrameCornerOffSetX1->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameCornerOffSetX1 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetX1->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetX1"));
        lineEdit_FrameCornerOffSetX1->setGeometry(QRect(30, 20, 101, 31));
        lineEdit_FrameCornerOffSetX1->setAlignment(Qt::AlignCenter);
        lineEdit_FrameCornerOffSetZ1 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetZ1->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetZ1"));
        lineEdit_FrameCornerOffSetZ1->setGeometry(QRect(30, 140, 101, 31));
        lineEdit_FrameCornerOffSetZ1->setAlignment(Qt::AlignCenter);
        pushButton_FrameCornerOffSetZ1 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetZ1->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetZ1"));
        pushButton_FrameCornerOffSetZ1->setGeometry(QRect(160, 140, 131, 31));
        pushButton_FrameCornerOffSetZ1->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameCornerOffSetY1 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetY1->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetY1"));
        lineEdit_FrameCornerOffSetY1->setGeometry(QRect(30, 80, 101, 31));
        lineEdit_FrameCornerOffSetY1->setAlignment(Qt::AlignCenter);
        pushButton_FrameCornerOffSetZ2 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetZ2->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetZ2"));
        pushButton_FrameCornerOffSetZ2->setGeometry(QRect(480, 140, 131, 31));
        pushButton_FrameCornerOffSetZ2->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameCornerOffSetZ2 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetZ2->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetZ2"));
        lineEdit_FrameCornerOffSetZ2->setGeometry(QRect(350, 140, 101, 31));
        lineEdit_FrameCornerOffSetZ2->setAlignment(Qt::AlignCenter);
        lineEdit_FrameCornerOffSetX2 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetX2->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetX2"));
        lineEdit_FrameCornerOffSetX2->setGeometry(QRect(350, 20, 101, 31));
        lineEdit_FrameCornerOffSetX2->setAlignment(Qt::AlignCenter);
        lineEdit_FrameCornerOffSetY2 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetY2->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetY2"));
        lineEdit_FrameCornerOffSetY2->setGeometry(QRect(350, 80, 101, 31));
        lineEdit_FrameCornerOffSetY2->setAlignment(Qt::AlignCenter);
        pushButton_FrameCornerOffSetY2 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetY2->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetY2"));
        pushButton_FrameCornerOffSetY2->setGeometry(QRect(480, 80, 131, 31));
        pushButton_FrameCornerOffSetY2->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_FrameCornerOffSetX2 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetX2->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetX2"));
        pushButton_FrameCornerOffSetX2->setGeometry(QRect(480, 20, 131, 31));
        pushButton_FrameCornerOffSetX2->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_FrameCornerOffSetZ3 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetZ3->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetZ3"));
        pushButton_FrameCornerOffSetZ3->setGeometry(QRect(160, 320, 131, 31));
        pushButton_FrameCornerOffSetZ3->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        pushButton_FrameCornerOffSetY3 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetY3->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetY3"));
        pushButton_FrameCornerOffSetY3->setGeometry(QRect(160, 260, 131, 31));
        pushButton_FrameCornerOffSetY3->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameCornerOffSetY3 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetY3->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetY3"));
        lineEdit_FrameCornerOffSetY3->setGeometry(QRect(30, 260, 101, 31));
        lineEdit_FrameCornerOffSetY3->setAlignment(Qt::AlignCenter);
        lineEdit_FrameCornerOffSetZ3 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetZ3->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetZ3"));
        lineEdit_FrameCornerOffSetZ3->setGeometry(QRect(30, 320, 101, 31));
        lineEdit_FrameCornerOffSetZ3->setAlignment(Qt::AlignCenter);
        pushButton_FrameCornerOffSetX3 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetX3->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetX3"));
        pushButton_FrameCornerOffSetX3->setGeometry(QRect(160, 200, 131, 31));
        pushButton_FrameCornerOffSetX3->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameCornerOffSetX3 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetX3->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetX3"));
        lineEdit_FrameCornerOffSetX3->setGeometry(QRect(30, 200, 101, 31));
        lineEdit_FrameCornerOffSetX3->setAlignment(Qt::AlignCenter);
        pushButton_FrameCornerOffSetZ4 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetZ4->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetZ4"));
        pushButton_FrameCornerOffSetZ4->setGeometry(QRect(480, 320, 131, 31));
        pushButton_FrameCornerOffSetZ4->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameCornerOffSetY4 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetY4->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetY4"));
        lineEdit_FrameCornerOffSetY4->setGeometry(QRect(350, 260, 101, 31));
        lineEdit_FrameCornerOffSetY4->setAlignment(Qt::AlignCenter);
        pushButton_FrameCornerOffSetX4 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetX4->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetX4"));
        pushButton_FrameCornerOffSetX4->setGeometry(QRect(480, 200, 131, 31));
        pushButton_FrameCornerOffSetX4->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameCornerOffSetX4 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetX4->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetX4"));
        lineEdit_FrameCornerOffSetX4->setGeometry(QRect(350, 200, 101, 31));
        lineEdit_FrameCornerOffSetX4->setAlignment(Qt::AlignCenter);
        pushButton_FrameCornerOffSetY4 = new QPushButton(page_7);
        pushButton_FrameCornerOffSetY4->setObjectName(QStringLiteral("pushButton_FrameCornerOffSetY4"));
        pushButton_FrameCornerOffSetY4->setGeometry(QRect(480, 260, 131, 31));
        pushButton_FrameCornerOffSetY4->setStyleSheet(QString::fromUtf8("font: 75 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lineEdit_FrameCornerOffSetZ4 = new QLineEdit(page_7);
        lineEdit_FrameCornerOffSetZ4->setObjectName(QStringLiteral("lineEdit_FrameCornerOffSetZ4"));
        lineEdit_FrameCornerOffSetZ4->setGeometry(QRect(350, 320, 101, 31));
        lineEdit_FrameCornerOffSetZ4->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_7);
        pushButton_PageIndex0 = new QPushButton(DlgRouteParam);
        pushButton_PageIndex0->setObjectName(QStringLiteral("pushButton_PageIndex0"));
        pushButton_PageIndex0->setGeometry(QRect(20, 20, 111, 41));
        pushButton_PageIndex1 = new QPushButton(DlgRouteParam);
        pushButton_PageIndex1->setObjectName(QStringLiteral("pushButton_PageIndex1"));
        pushButton_PageIndex1->setGeometry(QRect(20, 80, 111, 41));
        pushButton_PageIndex2 = new QPushButton(DlgRouteParam);
        pushButton_PageIndex2->setObjectName(QStringLiteral("pushButton_PageIndex2"));
        pushButton_PageIndex2->setGeometry(QRect(20, 140, 111, 41));
        pushButton_PageIndex3 = new QPushButton(DlgRouteParam);
        pushButton_PageIndex3->setObjectName(QStringLiteral("pushButton_PageIndex3"));
        pushButton_PageIndex3->setGeometry(QRect(20, 200, 111, 41));
        pushButton_PageIndex4 = new QPushButton(DlgRouteParam);
        pushButton_PageIndex4->setObjectName(QStringLiteral("pushButton_PageIndex4"));
        pushButton_PageIndex4->setGeometry(QRect(20, 260, 111, 41));
        pushButton_PageIndex5 = new QPushButton(DlgRouteParam);
        pushButton_PageIndex5->setObjectName(QStringLiteral("pushButton_PageIndex5"));
        pushButton_PageIndex5->setGeometry(QRect(20, 320, 111, 41));
        pushButton_PageIndex6 = new QPushButton(DlgRouteParam);
        pushButton_PageIndex6->setObjectName(QStringLiteral("pushButton_PageIndex6"));
        pushButton_PageIndex6->setGeometry(QRect(20, 380, 111, 41));

        retranslateUi(DlgRouteParam);

        stackedWidget->setCurrentIndex(6);


        QMetaObject::connectSlotsByName(DlgRouteParam);
    } // setupUi

    void retranslateUi(QDialog *DlgRouteParam)
    {
        DlgRouteParam->setWindowTitle(QApplication::translate("DlgRouteParam", "\346\211\213\346\234\272\345\244\226\350\247\202\346\243\200\346\265\213\350\275\250\350\277\271\350\256\276\347\275\256", Q_NULLPTR));
        pushButton_RunBackOffSetY->setText(QApplication::translate("DlgRouteParam", "RunBackOffSetY", Q_NULLPTR));
        pushButton_Circle14->setText(QApplication::translate("DlgRouteParam", "90\302\260\345\257\271\345\272\224\350\204\211\345\206\262", Q_NULLPTR));
        pushButton_P3->setText(QApplication::translate("DlgRouteParam", "\344\270\255\346\241\206\347\233\270\346\234\272", Q_NULLPTR));
        pushButton_P2->setText(QApplication::translate("DlgRouteParam", "\350\203\214\351\235\242\346\221\204\345\203\217\345\244\264", Q_NULLPTR));
        pushButton_BackGrat->setText(QApplication::translate("DlgRouteParam", "\345\220\216\345\205\211\346\240\205", Q_NULLPTR));
        pushButton_P1->setText(QApplication::translate("DlgRouteParam", "\346\255\243\350\203\214\345\220\214\350\275\264\345\205\211", Q_NULLPTR));
        pushButton_P4->setText(QApplication::translate("DlgRouteParam", "\347\277\273\350\275\254\346\234\272\346\236\204", Q_NULLPTR));
        pushButton_LightOpen->setText(QApplication::translate("DlgRouteParam", "\345\274\200\345\205\263\351\242\204\345\244\207", Q_NULLPTR));
        pushButton_FrontGrat->setText(QApplication::translate("DlgRouteParam", "\345\211\215\345\205\211\346\240\205", Q_NULLPTR));
        pushButton_P5->setText(QApplication::translate("DlgRouteParam", "\344\272\247\345\223\201\345\217\226\347\202\271", Q_NULLPTR));
        pushButton_Long->setText(QApplication::translate("DlgRouteParam", "\344\272\247\345\223\201\351\225\277\345\272\246", Q_NULLPTR));
        pushButton_FrontBackImageHeight->setText(QApplication::translate("DlgRouteParam", "\346\255\243\350\203\214\345\233\276\345\203\217\350\241\214\346\225\260", Q_NULLPTR));
        pushButton_Width->setText(QApplication::translate("DlgRouteParam", "\344\272\247\345\223\201\345\256\275\345\272\246", Q_NULLPTR));
        pushButton_ResetPointX->setText(QApplication::translate("DlgRouteParam", "\345\244\215\344\275\215\347\202\271X", Q_NULLPTR));
        pushButton_ResetPointY->setText(QApplication::translate("DlgRouteParam", "\345\244\215\344\275\215\347\202\271Y", Q_NULLPTR));
        pushButton_ResetPointZ->setText(QApplication::translate("DlgRouteParam", "\345\244\215\344\275\215\347\202\271Z", Q_NULLPTR));
        pushButton_GetPointZ->setText(QApplication::translate("DlgRouteParam", "\345\217\226\347\202\271Z", Q_NULLPTR));
        pushButton_GetPointY->setText(QApplication::translate("DlgRouteParam", "\345\217\226\347\202\271Y", Q_NULLPTR));
        pushButton_GetPointX->setText(QApplication::translate("DlgRouteParam", "\345\217\226\347\202\271X", Q_NULLPTR));
        pushButton_FrontOffSetX->setText(QApplication::translate("DlgRouteParam", "FrontOffSetX", Q_NULLPTR));
        pushButton_FrontOffSetY->setText(QApplication::translate("DlgRouteParam", "FrontOffSetY", Q_NULLPTR));
        pushButton_FrontOffSetZ->setText(QApplication::translate("DlgRouteParam", "FrontOffSetZ", Q_NULLPTR));
        pushButton_FrameOffSetX1->setText(QApplication::translate("DlgRouteParam", "FrameOffSetX1", Q_NULLPTR));
        pushButton_FrameOffSetZ1->setText(QApplication::translate("DlgRouteParam", "FrameOffSetZ1", Q_NULLPTR));
        pushButton_FrameOffSetY1->setText(QApplication::translate("DlgRouteParam", "FrameOffSetY1", Q_NULLPTR));
        pushButton_FrameStep->setText(QApplication::translate("DlgRouteParam", "FrameStep", Q_NULLPTR));
        pushButton_FrameOffSetY2->setText(QApplication::translate("DlgRouteParam", "FrameOffSetY2", Q_NULLPTR));
        pushButton_FrameOffSetX2->setText(QApplication::translate("DlgRouteParam", "FrameOffSetX2", Q_NULLPTR));
        pushButton_FrameOffSetZ2->setText(QApplication::translate("DlgRouteParam", "FrameOffSetZ2", Q_NULLPTR));
        pushButton_FrameOffSetX3->setText(QApplication::translate("DlgRouteParam", "FrameOffSetX3", Q_NULLPTR));
        pushButton_FrameOffSetY3->setText(QApplication::translate("DlgRouteParam", "FrameOffSetY3", Q_NULLPTR));
        pushButton_FrameOffSetZ3->setText(QApplication::translate("DlgRouteParam", "FrameOffSetZ3", Q_NULLPTR));
        pushButton_FrameOffSetZ4->setText(QApplication::translate("DlgRouteParam", "FrameOffSetZ4", Q_NULLPTR));
        pushButton_FrameOffSetX4->setText(QApplication::translate("DlgRouteParam", "FrameOffSetX4", Q_NULLPTR));
        pushButton_FrameOffSetY4->setText(QApplication::translate("DlgRouteParam", "FrameOffSetY4", Q_NULLPTR));
        pushButton_CylinderOffSetX->setText(QApplication::translate("DlgRouteParam", "CylinderOffSetX", Q_NULLPTR));
        pushButton_CylinderOffSetY->setText(QApplication::translate("DlgRouteParam", "CylinderOffSetY", Q_NULLPTR));
        pushButton_CylinderOffSetZ->setText(QApplication::translate("DlgRouteParam", "CylinderOffSetZ", Q_NULLPTR));
        pushButton_CameraOffSetZ->setText(QApplication::translate("DlgRouteParam", "CameraOffSetZ", Q_NULLPTR));
        pushButton_CameraOffSetX->setText(QApplication::translate("DlgRouteParam", "CameraOffSetX", Q_NULLPTR));
        pushButton_CameraOffSetY->setText(QApplication::translate("DlgRouteParam", "CameraOffSetY", Q_NULLPTR));
        pushButton_BackOffSetX->setText(QApplication::translate("DlgRouteParam", "BackOffSetX ", Q_NULLPTR));
        pushButton_BackOffSetY->setText(QApplication::translate("DlgRouteParam", "BackOffSetY", Q_NULLPTR));
        pushButton_BackOffSetZ->setText(QApplication::translate("DlgRouteParam", "BackOffSetZ", Q_NULLPTR));
        pushButton_FrameCornerOffSetY1->setText(QApplication::translate("DlgRouteParam", "CornerOffSetY1", Q_NULLPTR));
        pushButton_FrameCornerOffSetX1->setText(QApplication::translate("DlgRouteParam", "CornerOffSetX1", Q_NULLPTR));
        pushButton_FrameCornerOffSetZ1->setText(QApplication::translate("DlgRouteParam", "CornerOffSetZ1", Q_NULLPTR));
        pushButton_FrameCornerOffSetZ2->setText(QApplication::translate("DlgRouteParam", "CornerOffSetZ1", Q_NULLPTR));
        pushButton_FrameCornerOffSetY2->setText(QApplication::translate("DlgRouteParam", "CornerOffSetY1", Q_NULLPTR));
        pushButton_FrameCornerOffSetX2->setText(QApplication::translate("DlgRouteParam", "CornerOffSetX1", Q_NULLPTR));
        pushButton_FrameCornerOffSetZ3->setText(QApplication::translate("DlgRouteParam", "CornerOffSetZ1", Q_NULLPTR));
        pushButton_FrameCornerOffSetY3->setText(QApplication::translate("DlgRouteParam", "CornerOffSetY1", Q_NULLPTR));
        pushButton_FrameCornerOffSetX3->setText(QApplication::translate("DlgRouteParam", "CornerOffSetX1", Q_NULLPTR));
        pushButton_FrameCornerOffSetZ4->setText(QApplication::translate("DlgRouteParam", "CornerOffSetZ1", Q_NULLPTR));
        pushButton_FrameCornerOffSetX4->setText(QApplication::translate("DlgRouteParam", "CornerOffSetX1", Q_NULLPTR));
        pushButton_FrameCornerOffSetY4->setText(QApplication::translate("DlgRouteParam", "CornerOffSetY1", Q_NULLPTR));
        pushButton_PageIndex0->setText(QApplication::translate("DlgRouteParam", "FixedPoint", Q_NULLPTR));
        pushButton_PageIndex1->setText(QApplication::translate("DlgRouteParam", "\344\272\247\345\223\201\345\260\272\345\257\270", Q_NULLPTR));
        pushButton_PageIndex2->setText(QApplication::translate("DlgRouteParam", "\346\255\243\351\235\242", Q_NULLPTR));
        pushButton_PageIndex3->setText(QApplication::translate("DlgRouteParam", "\344\270\255\346\241\206\347\233\264\350\276\271", Q_NULLPTR));
        pushButton_PageIndex4->setText(QApplication::translate("DlgRouteParam", "\347\277\273\350\275\254\345\217\212\346\221\204\345\203\217\345\244\264", Q_NULLPTR));
        pushButton_PageIndex5->setText(QApplication::translate("DlgRouteParam", "\350\203\214\351\235\242", Q_NULLPTR));
        pushButton_PageIndex6->setText(QApplication::translate("DlgRouteParam", "\344\270\255\346\241\206R\350\247\222", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class DlgRouteParam: public Ui_DlgRouteParam {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DLGROUTEPARAM_H
